### ISSUE TITLE
Build OCI image CI/CD pipeline with Jenkins

### ISSUE THREAD

**Issue by JohnSundarrajJSR** [sloopstash/kickstart-jenkins#1]
Write a fully automated CI/CD pipeline script in Jenkins to build OCI images using the Dockerfiles available in the [kickstart-docker](https://github.com/sloopstash/kickstart-docker) repository and push them to DockerHub.

### CI/CD pipeline
- [x] Jenkins pipeline

**Comment by JohnSundarraj** [comment]
@Eliyaser please explain how to did this OCI pipeline task. I'll close this as of now.
